// Generated by https://quicktype.io
class Cast{

  List<Actor> actores = new List();

  Cast.fromJsonList(List<dynamic> jsonList){
    
    if(jsonList == null) return;

    jsonList.forEach((element) { 
      final actor = Actor.fromJsonMap(element);
      actores.add(actor);
    });
  }
}

class Actor {
  int castId;
  String character;
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  String profilePath;

  Actor({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  Actor.fromJsonMap(Map<String, dynamic>  json){
    this.castId = json['cast_Id'];
    this.character = json['character'];
    this.creditId= json['credit_Id'];
    this.gender= json['gender'];
    this.id= json['id'];
    this.name= json['name'];
    this.order= json['order'];
    this.profilePath= json['profile_path'];
  }

    getFoto(){

    // print(posterPath);

    if(profilePath != null){
      return 'https://image.tmdb.org/t/p/w500/$profilePath';
    }
    else{
       return 'https://www.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png';
    }
  }

}

