// Generated by https://quicktype.io
class Movies{

  List<Movie> items = new List();

  Movies();

  Movies.fromJsonList(List<dynamic> jsonList){
    if(jsonList == null){
      return;
    }

    jsonList.forEach((json) {
      Movie movie = new Movie.fromJsonMap(json);
      items.add(movie);
    });
  }

}


class Movie {
  double popularity;
  int voteCount;
  bool video;
  String posterPath;
  int id;
  bool adult;
  String backdropPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String title;
  double voteAverage;
  String overview;
  String releaseDate;
  String uniqueId;

  Movie({
    this.popularity,
    this.voteCount,
    this.video,
    this.posterPath,
    this.id,
    this.adult,
    this.backdropPath,
    this.originalLanguage,
    this.originalTitle,
    this.genreIds,
    this.title,
    this.voteAverage,
    this.overview,
    this.releaseDate,
  });

  Movie.fromJsonMap(Map<String, dynamic> json){
    this.popularity = json['popularity'] / 1;
    this.voteCount = json['vote_count'];
    this.video = json['video'];
    this.posterPath = json['poster_path'];
    this.id = json['id'];
    this.adult = json['adult'];
    this.backdropPath = json['backdrop_path'];
    this.originalLanguage = json['original_language'];
    this.originalTitle = json['original_title'];
    this.genreIds = json['genre_ids'].cast<int>();
    this.title = json['title'];
    this.voteAverage = json['vote_average'] / 1;
    this.overview = json['overview'];
    this.releaseDate = json['release_date'];
  }

  
  getPosterImg(){

    // print(posterPath);

    if(posterPath != null){
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    }
    else{
       return 'https://talleraltazor.com/wp-content/plugins/learnpress/assets/images/no-image.png';
    }
  }

  getBackgroundImage(){

    if(backdropPath != null){
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    }
    else{
      return 'https://talleraltazor.com/wp-content/plugins/learnpress/assets/images/no-image.png';
    }


  }
}


